# fly.toml file generated for fragrant-water-1016 on 2023-03-11T15:30:50Z

app = "fragrant-water-1016"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lhr"
processes = []

[env]
  ASPNETCORE_URLS = "http://+:8080"
  Cloudinary__ApiKey = "491748623171896"
  Cloudinary__CloudName = "dwcsdudyn"
  SendinBlue_User = "Sanctum"
  StripeSettings__PublishableKey = "pk_test_51L6i4NELV0KnfWeJgoqaVUo7jOES7YMDlWgtdHdwAXRsd2ExfVwP7sU9DhIyjES0JN7yly88c9HKpp0lBvtjIakX00pl6UGKM9"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
