namespace Domain.ListingAggregate.Enums
{
    // public enum PropertyType
    // {
    //     Houses,
    //     Flats,
    //     Bungalows,
    //     MobileHomes,
    //     CommercialProperty,
    //     Land,
    //     CharacterProperty,
    //     Parking,
    //     RetirementProperty,
    //     SharedProperty,
    // }

    public enum PropertyType
    {
        BarnConversion,
        BlockOfFlats,
        Bungalow,
        BusinessPark,
        Chalet,
        Chateau,
        Cottage,
        CountryHouse,
        Detached,
        DetachedBungalow,
        EndTerrace,
        Equestrian,
        Farm,
        Farmhouse,
        Finca,
        Flat,
        Hotel,
        Houseboat,
        Industrial,
        Land,
        Leisure,
        LightIndustrial,
        LinkDetached,
        Lodge,
        Longere,
        Maisonette,
        Mews,
        Office,
        ParkHome,
        Parking,
        PubBar,
        Restaurant,
        Retail,
        Riad,
        SemiDetached,
        SemiDetachedBungalow,
        Studio,
        Terraced,
        TerracedBungalow,
        TownHouse,
        Villa,
        Warehouse
    }
}