// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221217093534_PostgresInitial")]
    partial class PostgresInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "property_type", new[] { "barn_conversion", "block_of_flats", "bungalow", "business_park", "chalet", "chateau", "cottage", "country_house", "detached", "detached_bungalow", "end_terrace", "equestrian", "farm", "farmhouse", "finca", "flat", "hotel", "houseboat", "industrial", "land", "leisure", "light_industrial", "link_detached", "lodge", "longere", "maisonette", "mews", "office", "park_home", "parking", "pub_bar", "restaurant", "retail", "riad", "semi_detached", "semi_detached_bungalow", "studio", "terraced", "terraced_bungalow", "town_house", "villa", "warehouse" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.AppUserAggregate.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.AppUserAggregate.Objects.AppUserReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewerDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("ReviewerEmail")
                        .HasColumnType("text");

                    b.Property<string>("ReviewerPhone")
                        .HasColumnType("text");

                    b.Property<string>("ReviewerUsername")
                        .HasColumnType("text");

                    b.Property<int[]>("ServiceCategories")
                        .HasColumnType("integer[]");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("AppUserReview");
                });

            modelBuilder.Entity("Domain.AppUserAggregate.Objects.Photo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("Domain.CompanyAggregate.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompanyReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyRegistrationNumber")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegalName")
                        .HasColumnType("text");

                    b.Property<Guid?>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<int[]>("RedressSchemes")
                        .HasColumnType("integer[]");

                    b.Property<int[]>("ServiceCategories")
                        .HasColumnType("integer[]");

                    b.Property<string>("ServiceLocations")
                        .HasColumnType("text");

                    b.Property<string>("SummaryDescription")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Domain.CompanyAggregate.CompanyContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLogo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyContent");
                });

            modelBuilder.Entity("Domain.CompanyAggregate.CompanyDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Heading")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyDescription");
                });

            modelBuilder.Entity("Domain.CompanyAggregate.CompanyReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewerDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("ReviewerEmail")
                        .HasColumnType("text");

                    b.Property<string>("ReviewerPhone")
                        .HasColumnType("text");

                    b.Property<string>("ReviewerUsername")
                        .HasColumnType("text");

                    b.Property<int[]>("ServiceCategories")
                        .HasColumnType("integer[]");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyReview");
                });

            modelBuilder.Entity("Domain.CompanyAggregate.Insurance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IndemnityLimit")
                        .HasColumnType("text");

                    b.Property<string>("PolicyNumber")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Insurance");
                });

            modelBuilder.Entity("Domain.InvoiceAggregate.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("text");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<long>("VatPercentage")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Domain.InvoiceAggregate.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<long>("VatPercentage")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItem");
                });

            modelBuilder.Entity("Domain.JobAggregate.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("FinishBy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JobLifeCycle")
                        .HasColumnType("integer");

                    b.Property<int[]>("ServiceCategories")
                        .HasColumnType("integer[]");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Domain.JobAggregate.Objects.JobContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobContent");
                });

            modelBuilder.Entity("Domain.JobNetwork", b =>
                {
                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("AppUserId", "JobId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("JobId");

                    b.ToTable("JobNetwork");
                });

            modelBuilder.Entity("Domain.ListingAggregate.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("Accessibility")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AdministrationFees")
                        .HasColumnType("text");

                    b.Property<double>("AnnualBusinessRates")
                        .HasColumnType("double precision");

                    b.Property<int>("AvailableBedrooms")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AvailableFromDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Basement")
                        .HasColumnType("boolean");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int[]>("BillsIncluded")
                        .HasColumnType("integer[]");

                    b.Property<bool>("BurglarAlarm")
                        .HasColumnType("boolean");

                    b.Property<bool>("BusinessForSale")
                        .HasColumnType("boolean");

                    b.Property<int[]>("BuyerIncentives")
                        .HasColumnType("integer[]");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("CentralHeating")
                        .HasColumnType("integer");

                    b.Property<bool>("ChainFree")
                        .HasColumnType("boolean");

                    b.Property<List<string>>("CommercialUseClass")
                        .HasColumnType("text[]");

                    b.Property<string>("CompanyReference")
                        .HasColumnType("text");

                    b.Property<int[]>("ConnectedUtilities")
                        .HasColumnType("integer[]");

                    b.Property<bool>("Conservatory")
                        .HasColumnType("boolean");

                    b.Property<int>("ConstructionYear")
                        .HasColumnType("integer");

                    b.Property<int>("CookerType")
                        .HasColumnType("integer");

                    b.Property<int>("CouncilTaxBand")
                        .HasColumnType("integer");

                    b.Property<int>("DecorativeCondition")
                        .HasColumnType("integer");

                    b.Property<double>("Deposit")
                        .HasColumnType("double precision");

                    b.Property<bool>("DoubleGlazing")
                        .HasColumnType("boolean");

                    b.Property<List<string>>("FeatureList")
                        .HasColumnType("text[]");

                    b.Property<bool>("FeatureProperty")
                        .HasColumnType("boolean");

                    b.Property<bool>("Fireplace")
                        .HasColumnType("boolean");

                    b.Property<bool>("FishingRights")
                        .HasColumnType("boolean");

                    b.Property<List<int>>("FloorLevels")
                        .HasColumnType("integer[]");

                    b.Property<int>("Floors")
                        .HasColumnType("integer");

                    b.Property<bool>("Freezer")
                        .HasColumnType("boolean");

                    b.Property<bool>("Fridge")
                        .HasColumnType("boolean");

                    b.Property<int>("FurnishedState")
                        .HasColumnType("integer");

                    b.Property<double>("GroundRent")
                        .HasColumnType("double precision");

                    b.Property<bool>("Gym")
                        .HasColumnType("boolean");

                    b.Property<int>("LifeCycleStatus")
                        .HasColumnType("integer");

                    b.Property<int>("ListedBuildingGrade")
                        .HasColumnType("integer");

                    b.Property<string>("ListingReference")
                        .HasColumnType("text");

                    b.Property<int>("LivingRooms")
                        .HasColumnType("integer");

                    b.Property<bool>("Loft")
                        .HasColumnType("boolean");

                    b.Property<bool>("NewBuild")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OpenDay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Outbuildings")
                        .HasColumnType("boolean");

                    b.Property<int[]>("OutsideSpaces")
                        .HasColumnType("integer[]");

                    b.Property<int[]>("Parking")
                        .HasColumnType("integer[]");

                    b.Property<bool>("PetsAllowed")
                        .HasColumnType("boolean");

                    b.Property<bool>("PorterSecurity")
                        .HasColumnType("boolean");

                    b.Property<int>("PropertyType")
                        .HasColumnType("integer");

                    b.Property<int>("RateableValue")
                        .HasColumnType("integer");

                    b.Property<int>("RentalTerm")
                        .HasColumnType("integer");

                    b.Property<bool>("Repossession")
                        .HasColumnType("boolean");

                    b.Property<bool>("Retirement")
                        .HasColumnType("boolean");

                    b.Property<int>("SapRating")
                        .HasColumnType("integer");

                    b.Property<bool>("Serviced")
                        .HasColumnType("boolean");

                    b.Property<bool>("SharedAccommodation")
                        .HasColumnType("boolean");

                    b.Property<string>("SummaryDescription")
                        .HasColumnType("text");

                    b.Property<bool>("SwimmingPool")
                        .HasColumnType("boolean");

                    b.Property<bool>("Tenanted")
                        .HasColumnType("boolean");

                    b.Property<bool>("TennisCourt")
                        .HasColumnType("boolean");

                    b.Property<int>("Tenure")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBedrooms")
                        .HasColumnType("integer");

                    b.Property<bool>("UtilityRoom")
                        .HasColumnType("boolean");

                    b.Property<bool>("WaterFront")
                        .HasColumnType("boolean");

                    b.Property<bool>("WoodFloors")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CompanyReference");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("Domain.ListingAggregate.Objects.Areas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ListingId")
                        .IsUnique();

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Domain.ListingAggregate.Objects.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("Content");
                });

            modelBuilder.Entity("Domain.ListingAggregate.Objects.DetailedDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Heading")
                        .HasColumnType("text");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("DetailedDescription");
                });

            modelBuilder.Entity("Domain.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyReference")
                        .HasColumnType("text");

                    b.Property<int>("ContractLength")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<long>("VatPercentage")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Membership");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "ecbdb05a-8ee2-4abe-9d8e-a63d4baded22",
                            Name = "Company",
                            NormalizedName = "COMPANY"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "6832cb5b-cd2d-4dfd-b430-ca71ef6416be",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "835f6522-0d42-47b0-a7fc-79686fd36f4d",
                            Name = "Agency",
                            NormalizedName = "AGENCY"
                        },
                        new
                        {
                            Id = "4",
                            ConcurrencyStamp = "88383a9c-1c76-49f0-a4c2-6fcda96309d8",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.AppUserAggregate.Objects.AppUserReview", b =>
                {
                    b.HasOne("Domain.AppUserAggregate.AppUser", null)
                        .WithMany("Reviews")
                        .HasForeignKey("AppUserId");
                });

            modelBuilder.Entity("Domain.AppUserAggregate.Objects.Photo", b =>
                {
                    b.HasOne("Domain.AppUserAggregate.AppUser", null)
                        .WithMany("Photos")
                        .HasForeignKey("AppUserId");
                });

            modelBuilder.Entity("Domain.CompanyAggregate.Company", b =>
                {
                    b.HasOne("Domain.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId");

                    b.OwnsOne("Domain.CompanyAggregate.CompanyAddress", "CompanyAddress", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Country")
                                .HasColumnType("integer");

                            b1.Property<string>("County")
                                .HasColumnType("text");

                            b1.Property<string>("Locality")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PropertyNumberOrName")
                                .HasColumnType("text");

                            b1.Property<string>("StreetName")
                                .HasColumnType("text");

                            b1.Property<string>("TownOrCity")
                                .HasColumnType("text");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");

                            b1.OwnsOne("Domain.LocationAggregate.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("CompanyAddressCompanyId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");

                                    b2.HasKey("CompanyAddressCompanyId");

                                    b2.ToTable("Companies");

                                    b2.WithOwner()
                                        .HasForeignKey("CompanyAddressCompanyId");
                                });

                            b1.Navigation("Coordinates");
                        });

                    b.OwnsOne("Domain.CompanyAggregate.CompanyContacts", "CompanyContacts", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .HasColumnType("text");

                            b1.Property<string>("Website")
                                .HasColumnType("text");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("CompanyAddress");

                    b.Navigation("CompanyContacts");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Domain.CompanyAggregate.CompanyContent", b =>
                {
                    b.HasOne("Domain.CompanyAggregate.Company", "Company")
                        .WithMany("CompanyContents")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.CompanyAggregate.CompanyDescription", b =>
                {
                    b.HasOne("Domain.CompanyAggregate.Company", "Company")
                        .WithMany("CompanyDescriptions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.CompanyAggregate.CompanyReview", b =>
                {
                    b.HasOne("Domain.CompanyAggregate.Company", null)
                        .WithMany("Reviews")
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("Domain.CompanyAggregate.Insurance", b =>
                {
                    b.HasOne("Domain.CompanyAggregate.Company", "Company")
                        .WithMany("Insurances")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.InvoiceAggregate.Invoice", b =>
                {
                    b.HasOne("Domain.Membership", null)
                        .WithMany("Invoices")
                        .HasForeignKey("MembershipId");
                });

            modelBuilder.Entity("Domain.InvoiceAggregate.InvoiceItem", b =>
                {
                    b.HasOne("Domain.InvoiceAggregate.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Domain.JobAggregate.Job", b =>
                {
                    b.OwnsOne("Domain.JobAggregate.Objects.JobLocation", "JobLocation", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Country")
                                .HasColumnType("integer");

                            b1.Property<string>("County")
                                .HasColumnType("text");

                            b1.Property<string>("Locality")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PropertyNumberOrName")
                                .HasColumnType("text");

                            b1.Property<string>("StreetName")
                                .HasColumnType("text");

                            b1.Property<string>("TownOrCity")
                                .HasColumnType("text");

                            b1.HasKey("JobId");

                            b1.ToTable("Jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobId");

                            b1.OwnsOne("Domain.LocationAggregate.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("JobLocationJobId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");

                                    b2.HasKey("JobLocationJobId");

                                    b2.ToTable("Jobs");

                                    b2.WithOwner()
                                        .HasForeignKey("JobLocationJobId");
                                });

                            b1.Navigation("Coordinates");
                        });

                    b.Navigation("JobLocation");
                });

            modelBuilder.Entity("Domain.JobAggregate.Objects.JobContent", b =>
                {
                    b.HasOne("Domain.JobAggregate.Job", "Job")
                        .WithMany("JobContents")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Domain.JobNetwork", b =>
                {
                    b.HasOne("Domain.AppUserAggregate.AppUser", "AppUser")
                        .WithMany("Jobs")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.InvoiceAggregate.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId");

                    b.HasOne("Domain.JobAggregate.Job", "Job")
                        .WithMany("Networks")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Invoice");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Domain.ListingAggregate.Listing", b =>
                {
                    b.HasOne("Domain.CompanyAggregate.Company", "Company")
                        .WithMany("Listings")
                        .HasForeignKey("CompanyReference")
                        .HasPrincipalKey("CompanyReference");

                    b.OwnsOne("Domain.ListingAggregate.Objects.EpcRatings", "EpcRatings", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<int>("EerCurrentRating")
                                .HasColumnType("integer");

                            b1.Property<int>("EerPotentialRating")
                                .HasColumnType("integer");

                            b1.Property<int>("EirCurrentRating")
                                .HasColumnType("integer");

                            b1.Property<int>("EirPotentialRating")
                                .HasColumnType("integer");

                            b1.HasKey("ListingId");

                            b1.ToTable("Listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.OwnsOne("Domain.ListingAggregate.Objects.LeaseExpiry", "LeaseExpiry", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExpiryDate")
                                .HasColumnType("text");

                            b1.Property<int>("YearsRemaining")
                                .HasColumnType("integer");

                            b1.HasKey("ListingId");

                            b1.ToTable("Listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.OwnsOne("Domain.ListingAggregate.Objects.ListingLocation", "ListingLocation", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Country")
                                .HasColumnType("integer");

                            b1.Property<string>("County")
                                .HasColumnType("text");

                            b1.Property<string>("Locality")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PropertyNumberOrName")
                                .HasColumnType("text");

                            b1.Property<string>("StreetName")
                                .HasColumnType("text");

                            b1.Property<string>("TownOrCity")
                                .HasColumnType("text");

                            b1.HasKey("ListingId");

                            b1.ToTable("Listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");

                            b1.OwnsOne("Domain.LocationAggregate.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("ListingLocationListingId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");

                                    b2.HasKey("ListingLocationListingId");

                                    b2.ToTable("Listings");

                                    b2.WithOwner()
                                        .HasForeignKey("ListingLocationListingId");
                                });

                            b1.Navigation("Coordinates");
                        });

                    b.OwnsOne("Domain.ListingAggregate.Objects.MinimumContractLength", "MinimumContractLength", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MinimumLength")
                                .HasColumnType("integer");

                            b1.Property<int>("Units")
                                .HasColumnType("integer");

                            b1.HasKey("ListingId");

                            b1.ToTable("Listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.OwnsOne("Domain.ListingAggregate.Objects.Pricing", "Pricing", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Auction")
                                .HasColumnType("boolean");

                            b1.Property<int>("Currency")
                                .HasColumnType("integer");

                            b1.Property<double>("Price")
                                .HasColumnType("double precision");

                            b1.Property<int>("PriceQualifier")
                                .HasColumnType("integer");

                            b1.Property<int>("RentFrequency")
                                .HasColumnType("integer");

                            b1.Property<int>("TransactionType")
                                .HasColumnType("integer");

                            b1.HasKey("ListingId");

                            b1.ToTable("Listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");

                            b1.OwnsOne("Domain.ListingAggregate.Objects.PricePerUnitArea", "PricePerUnitArea", b2 =>
                                {
                                    b2.Property<Guid>("PricingListingId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Price")
                                        .HasColumnType("double precision");

                                    b2.Property<int>("Units")
                                        .HasColumnType("integer");

                                    b2.HasKey("PricingListingId");

                                    b2.ToTable("Listings");

                                    b2.WithOwner()
                                        .HasForeignKey("PricingListingId");
                                });

                            b1.Navigation("PricePerUnitArea");
                        });

                    b.OwnsOne("Domain.ListingAggregate.Objects.ServiceCharge", "ServiceCharge", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Charge")
                                .HasColumnType("double precision");

                            b1.Property<int>("Frequency")
                                .HasColumnType("integer");

                            b1.Property<int>("PerUnitAreaUnits")
                                .HasColumnType("integer");

                            b1.HasKey("ListingId");

                            b1.ToTable("Listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.OwnsOne("Domain.ListingAggregate.Objects.TenantEligibility", "TenantEligibility", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Dss")
                                .HasColumnType("integer");

                            b1.Property<int>("Students")
                                .HasColumnType("integer");

                            b1.HasKey("ListingId");

                            b1.ToTable("Listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.Navigation("Company");

                    b.Navigation("EpcRatings");

                    b.Navigation("LeaseExpiry");

                    b.Navigation("ListingLocation");

                    b.Navigation("MinimumContractLength");

                    b.Navigation("Pricing");

                    b.Navigation("ServiceCharge");

                    b.Navigation("TenantEligibility");
                });

            modelBuilder.Entity("Domain.ListingAggregate.Objects.Areas", b =>
                {
                    b.HasOne("Domain.ListingAggregate.Listing", "Listing")
                        .WithOne("Areas")
                        .HasForeignKey("Domain.ListingAggregate.Objects.Areas", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ListingAggregate.Objects.Area", "External", b1 =>
                        {
                            b1.Property<Guid>("AreasId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Units")
                                .HasColumnType("integer");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision");

                            b1.HasKey("AreasId");

                            b1.ToTable("Areas");

                            b1.WithOwner()
                                .HasForeignKey("AreasId");
                        });

                    b.OwnsOne("Domain.ListingAggregate.Objects.Area", "Internal", b1 =>
                        {
                            b1.Property<Guid>("AreasId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Units")
                                .HasColumnType("integer");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision");

                            b1.HasKey("AreasId");

                            b1.ToTable("Areas");

                            b1.WithOwner()
                                .HasForeignKey("AreasId");
                        });

                    b.Navigation("External");

                    b.Navigation("Internal");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Domain.ListingAggregate.Objects.Content", b =>
                {
                    b.HasOne("Domain.ListingAggregate.Listing", "Listing")
                        .WithMany("Contents")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Domain.ListingAggregate.Objects.DetailedDescription", b =>
                {
                    b.HasOne("Domain.ListingAggregate.Listing", "Listing")
                        .WithMany("DetailedDescriptions")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ListingAggregate.Objects.Dimensions", "Dimensions", b1 =>
                        {
                            b1.Property<int>("DetailedDescriptionId")
                                .HasColumnType("integer");

                            b1.Property<double>("Length")
                                .HasColumnType("double precision");

                            b1.Property<int>("Unit")
                                .HasColumnType("integer");

                            b1.Property<double>("Width")
                                .HasColumnType("double precision");

                            b1.HasKey("DetailedDescriptionId");

                            b1.ToTable("DetailedDescription");

                            b1.WithOwner()
                                .HasForeignKey("DetailedDescriptionId");
                        });

                    b.Navigation("Dimensions");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.AppUserAggregate.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.AppUserAggregate.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.AppUserAggregate.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.AppUserAggregate.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.AppUserAggregate.AppUser", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Photos");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Domain.CompanyAggregate.Company", b =>
                {
                    b.Navigation("CompanyContents");

                    b.Navigation("CompanyDescriptions");

                    b.Navigation("Insurances");

                    b.Navigation("Listings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Domain.InvoiceAggregate.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.JobAggregate.Job", b =>
                {
                    b.Navigation("JobContents");

                    b.Navigation("Networks");
                });

            modelBuilder.Entity("Domain.ListingAggregate.Listing", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Contents");

                    b.Navigation("DetailedDescriptions");
                });

            modelBuilder.Entity("Domain.Membership", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
